#!/bin/sh

# Command: touchall
#
# Function: Touches all files in the specified directory.
#	        This is then repeated for all subdirectories.

VERSION=1.0

showhelp () {
	echo Usage: touchall [OPTION...] [DIRECTORY]
	echo
	echo The default directory is the current directory.
	echo
	echo Description: Touches all files in the directory.
	echo
	echo Options:
	echo '  -r              Touches all files in the directory'
	echo '                  and subdirectories recursively.'
	echo '  -v, --version   Shows the version of the script.'
	echo '  --help          Shows this help text.'
	echo
	echo Return codes:
	echo '  0   No errors.'
	echo '  1   Error encountered.'

	return 0
}

showversion () {
	echo touchall, version $VERSION

	return 0
}

DIR=.
FLG='-maxdepth 1'

OPTCNT=0

# Parse option flags
while getopts ':rv' OPT; do
	# Case statement in case additional options
	# are desired at a later point.
	case $OPT in
		r)
			# Allow recursion, will hit all
			# subdirectories as well.
			FLG=''

			# Incrememnt the options counter.
			OPTCNT=$((OPTCNT + 1))
			;;
		v)
			# Show the version.
			showversion
			exit 0
			;;
		h)
			# Print help
			showhelp
			exit 0
			;;
		?)
			# No option found.  Do nothing.
			# This is to deal with '--'.
			;;
		*)
			# Unknown option.
			echo Unknown option provided.
			echo
			showhelp
			exit 1
	esac
done

if [ $# -gt 0 ] && [ $OPTCNT -le $# ]; then
	shift $((OPTCNT))
fi

if [ -z $1 ]; then
	ARG=$1
	echo $ARG

	case $OPT in
		?)
			# Print help
			showhelp
			exit 0
			;;
		*)
			# Checking to see if the argument is
			# a file.
			if [ -d $ARG ]; then
				DIR = $ARG
			else
				echo Cannot access the directory: $ARG
			fi
	esac
fi

find $DIR $FLG -exec touch {} \;